query loadMenu {
  loadMenu: menus{
    edges{
      node{
        slug
        menuItems{
          edges{
            node{
              label
              url
              id
            }
          }
        }
      }
    }
  }
}
